"""Initial 3D cadastral schema

Revision ID: 730b2902b149
Revises: 
Create Date: 2026-08-25 21:20:01.873714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730b2902b149'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('conflict_id', sa.String(length=64), nullable=False),
    sa.Column('property_a', sa.String(length=64), nullable=False),
    sa.Column('property_a_name', sa.String(length=255), nullable=False),
    sa.Column('property_b', sa.String(length=64), nullable=False),
    sa.Column('property_b_name', sa.String(length=255), nullable=False),
    sa.Column('overlap_exists', sa.Boolean(), nullable=False),
    sa.Column('overlap_volume_m3', sa.Float(), nullable=False),
    sa.Column('conflict_type', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('overlap_min_x', sa.Float(), nullable=False),
    sa.Column('overlap_max_x', sa.Float(), nullable=False),
    sa.Column('overlap_min_y', sa.Float(), nullable=False),
    sa.Column('overlap_max_y', sa.Float(), nullable=False),
    sa.Column('overlap_min_z', sa.Float(), nullable=False),
    sa.Column('overlap_max_z', sa.Float(), nullable=False),
    sa.Column('overlap_width_m', sa.Float(), nullable=False),
    sa.Column('overlap_height_m', sa.Float(), nullable=False),
    sa.Column('overlap_depth_m', sa.Float(), nullable=False),
    sa.Column('processing_method', sa.String(length=128), nullable=False),
    sa.Column('data_classification', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('conflict_id')
    )
    op.create_index(op.f('ix_conflicts_conflict_id'), 'conflicts', ['conflict_id'], unique=False)
    op.create_index(op.f('ix_conflicts_property_a'), 'conflicts', ['property_a'], unique=False)
    op.create_index(op.f('ix_conflicts_property_b'), 'conflicts', ['property_b'], unique=False)
    op.create_table('parcels',
    sa.Column('parcel_id', sa.String(length=64), nullable=False),
    sa.Column('survey_number', sa.String(length=64), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('ulpin_base', sa.String(length=128), nullable=False),
    sa.Column('coordinate_reference', sa.String(length=255), nullable=False),
    sa.Column('min_x', sa.Float(), nullable=False),
    sa.Column('max_x', sa.Float(), nullable=False),
    sa.Column('min_z', sa.Float(), nullable=False),
    sa.Column('max_z', sa.Float(), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=False),
    sa.Column('depth_m', sa.Float(), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('elevation_min_m', sa.Float(), nullable=False),
    sa.Column('elevation_max_m', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('data_classification', sa.String(length=128), nullable=False),
    sa.Column('gnss_cors_note', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('parcel_id')
    )
    op.create_index(op.f('ix_parcels_parcel_id'), 'parcels', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_parcels_ulpin_base'), 'parcels', ['ulpin_base'], unique=True)
    op.create_table('topology_validations',
    sa.Column('validation_id', sa.String(length=64), nullable=False),
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=False),
    sa.Column('overall_status', sa.String(length=32), nullable=False),
    sa.Column('passed_check_count', sa.Integer(), nullable=False),
    sa.Column('failed_check_count', sa.Integer(), nullable=False),
    sa.Column('processing_method', sa.String(length=128), nullable=False),
    sa.Column('data_classification', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('validation_id')
    )
    op.create_index(op.f('ix_topology_validations_property_id'), 'topology_validations', ['property_id'], unique=False)
    op.create_index(op.f('ix_topology_validations_validation_id'), 'topology_validations', ['validation_id'], unique=False)
    op.create_table('lidar_surveys',
    sa.Column('survey_id', sa.String(length=64), nullable=False),
    sa.Column('parcel_id', sa.String(length=64), nullable=True),
    sa.Column('data_source_type', sa.String(length=128), nullable=False),
    sa.Column('sensor_model', sa.String(length=128), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('min_x', sa.Float(), nullable=False),
    sa.Column('max_x', sa.Float(), nullable=False),
    sa.Column('min_y', sa.Float(), nullable=False),
    sa.Column('max_y', sa.Float(), nullable=False),
    sa.Column('min_z', sa.Float(), nullable=False),
    sa.Column('max_z', sa.Float(), nullable=False),
    sa.Column('span_x', sa.Float(), nullable=False),
    sa.Column('vertical_span', sa.Float(), nullable=False),
    sa.Column('span_z', sa.Float(), nullable=False),
    sa.Column('enclosure_volume_m3', sa.Float(), nullable=False),
    sa.Column('bounding_extent', sa.String(length=128), nullable=False),
    sa.Column('data_classification', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.parcel_id'], ),
    sa.PrimaryKeyConstraint('survey_id')
    )
    op.create_index(op.f('ix_lidar_surveys_survey_id'), 'lidar_surveys', ['survey_id'], unique=False)
    op.create_table('properties',
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=255), nullable=False),
    sa.Column('property_type', sa.String(length=128), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('ulpin', sa.String(length=128), nullable=False),
    sa.Column('parcel_id', sa.String(length=64), nullable=False),
    sa.Column('elevation_min_m', sa.Float(), nullable=False),
    sa.Column('elevation_max_m', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.String(length=128), nullable=False),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('conflict_desc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.parcel_id'], ),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_index(op.f('ix_properties_parcel_id'), 'properties', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_properties_property_id'), 'properties', ['property_id'], unique=False)
    op.create_index(op.f('ix_properties_ulpin'), 'properties', ['ulpin'], unique=True)
    op.create_table('topology_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('validation_id', sa.String(length=64), nullable=False),
    sa.Column('check_id', sa.String(length=32), nullable=False),
    sa.Column('check_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('related_property_id', sa.String(length=64), nullable=True),
    sa.Column('measured_value', sa.String(length=255), nullable=False),
    sa.Column('expected_condition', sa.String(length=255), nullable=False),
    sa.Column('processing_method', sa.String(length=128), nullable=False),
    sa.Column('data_classification', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['validation_id'], ['topology_validations.validation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_checks_validation_id'), 'topology_checks', ['validation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topology_checks_validation_id'), table_name='topology_checks')
    op.drop_table('topology_checks')
    op.drop_index(op.f('ix_properties_ulpin'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_parcel_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_lidar_surveys_survey_id'), table_name='lidar_surveys')
    op.drop_table('lidar_surveys')
    op.drop_index(op.f('ix_topology_validations_validation_id'), table_name='topology_validations')
    op.drop_index(op.f('ix_topology_validations_property_id'), table_name='topology_validations')
    op.drop_table('topology_validations')
    op.drop_index(op.f('ix_parcels_ulpin_base'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_parcel_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_conflicts_property_b'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_property_a'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_conflict_id'), table_name='conflicts')
    op.drop_table('conflicts')
    # ### end Alembic commands ###
